# Platform and deployment target
platform :ios, '13.0'

# Workaround for Cocoapods issue
install! 'cocoapods', :deterministic_uuids => false

# Use the correct path for Flutter
flutter_application_path = '..'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install all Flutter pods
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
